# Generated by Django 5.2.4 on 2026-06-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('author', models.CharField(default='김지훈', max_length=30)),
                ('avatar', models.CharField(default='김', max_length=2)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('liked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(default='김지훈', max_length=30)),
                ('avatar', models.CharField(default='김', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='api.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
