# Generated by Django 5.2.4 on 2026-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('spending_summary', '소비 분석'), ('chat', '챗봇 상담'), ('transaction_parse', '결제내역 입력 보정'), ('purchase_plan', '소비 계획 분석')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('ai_mode', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['analysis_type', '-created_at'], name='api_aianaly_analysi_8143c4_idx')],
            },
        ),
    ]
