# Generated by Django 5.2.4 on 2026-06-23 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aianalysisrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=40, unique=True)),
                ('card_id', models.CharField(max_length=20)),
                ('merchant_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('approved_at', models.DateTimeField()),
                ('icon', models.CharField(default='💳', max_length=8)),
                ('address', models.CharField(blank=True, default='직접 입력', max_length=200)),
                ('source_text', models.TextField(blank=True, default='')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-approved_at', '-id'],
                'indexes': [models.Index(fields=['card_id', '-approved_at'], name='api_transac_card_id_ceb47f_idx'), models.Index(fields=['category', '-approved_at'], name='api_transac_categor_269b5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('plan_type', models.CharField(default='기타', max_length=40)),
                ('expense_mode', models.CharField(default='planned-extra', max_length=40)),
                ('total_budget', models.PositiveIntegerField(default=0)),
                ('start_month', models.CharField(max_length=7)),
                ('end_month', models.CharField(max_length=7)),
                ('status', models.CharField(default='작성 중', max_length=30)),
                ('selected_scenario_id', models.CharField(blank=True, default='', max_length=40)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('items', models.JSONField(blank=True, default=list)),
                ('scenarios', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_plans', to='api.aianalysisrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_purchas_created_2f5b20_idx'), models.Index(fields=['status', '-created_at'], name='api_purchas_status_53d9df_idx')],
            },
        ),
    ]
