# Generated by Django 5.2.4 on 2026-06-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_purchaseplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20, unique=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['display_order', 'id'], name='api_ownedca_display_fde7d3_idx')],
            },
        ),
    ]
