# Generated by Django 5.2.4 on 2026-06-23 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_aianalysisrecord_cache_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(default='email', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='api_authses_token_h_d58115_idx'), models.Index(fields=['user', '-created_at'], name='api_authses_user_id_0cbc27_idx'), models.Index(fields=['expires_at'], name='api_authses_expires_2d6a0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kakao', '카카오'), ('naver', '네이버')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('raw_profile', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'id'],
                'indexes': [models.Index(fields=['provider', 'provider_user_id'], name='api_sociala_provide_6ec298_idx'), models.Index(fields=['email'], name='api_sociala_email_94390c_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='api_social_provider_user_uniq')],
            },
        ),
    ]
