# Generated by Django 5.2.4 on 2026-06-23 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def attach_existing_rows_to_demo_user(apps, schema_editor):
    auth_app, auth_model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(auth_app, auth_model)
    username = 'demo'
    if User.objects.filter(username=username).exclude(email='demo@carch.local').exists():
        suffix = 1
        while User.objects.filter(username=f'demo{suffix}').exists():
            suffix += 1
        username = f'demo{suffix}'
    user, created = User.objects.get_or_create(
        email='demo@carch.local',
        defaults={
            'username': username,
            'first_name': '남주현',
        },
    )
    if not user.first_name:
        user.first_name = '남주현'
        user.save(update_fields=['first_name'])

    for model_name in ['AIAnalysisRecord', 'OwnedCard', 'PurchasePlan', 'Transaction']:
        model = apps.get_model('api', model_name)
        model.objects.filter(user__isnull=True).update(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_authsession_socialaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownedcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownedcard',
            name='card_id',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(attach_existing_rows_to_demo_user, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='aianalysisrecord',
            index=models.Index(fields=['user', 'analysis_type', '-created_at'], name='api_aianaly_user_id_7c0d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ownedcard',
            index=models.Index(fields=['user', 'display_order', 'id'], name='api_ownedca_user_id_e4389d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseplan',
            index=models.Index(fields=['user', '-created_at'], name='api_purchas_user_id_ef509e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-approved_at'], name='api_transac_user_id_25536b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownedcard',
            constraint=models.UniqueConstraint(fields=('user', 'card_id'), name='api_owned_user_card_uniq'),
        ),
    ]
