# Generated by Django 5.2.4 on 2026-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transaction_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='analysis_type',
            field=models.CharField(choices=[('spending_summary', '소비 분석'), ('chat', '챗봇 상담'), ('transaction_parse', '결제내역 입력 보정'), ('purchase_plan', '소비 계획 분석'), ('card_recommendation', '카드 추천 판단')], max_length=40),
        ),
    ]
