# Generated by Django 5.2.15 on 2026-06-24 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_card_recommendation_analysis_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('total_goal', models.PositiveIntegerField(blank=True, null=True)),
                ('category_budgets', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['user', 'month'], name='api_budget_user_id_3c0ce1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'month'), name='api_budget_user_month_uniq')],
            },
        ),
    ]
