TRANSACTIONS = [
    {
        'id': 't1',
        'cardId': '10029',
        'merchantName': '컴포즈커피 역삼센터필드점',
        'category': '카페',
        'amount': -3800,
        'approvedAt': '2026-06-23T08:42:00+09:00',
        'icon': '☕',
        'address': '서울 강남구 테헤란로 231',
    },
    {
        'id': 't2',
        'cardId': '10029',
        'merchantName': '샐러디 역삼점',
        'category': '식비',
        'amount': -10900,
        'approvedAt': '2026-06-23T12:18:00+09:00',
        'icon': '🥗',
        'address': '서울 강남구 테헤란로 152',
    },
    {
        'id': 't3',
        'cardId': '10612',
        'merchantName': '스포애니 봉천점',
        'category': '헬스',
        'amount': -59000,
        'approvedAt': '2026-06-22T21:20:00+09:00',
        'icon': '🏋️',
        'address': '서울 관악구 봉천로 463',
    },
    {
        'id': 't4',
        'cardId': '10029',
        'merchantName': '카카오T 봉천→역삼',
        'category': '교통',
        'amount': -13600,
        'approvedAt': '2026-06-22T08:06:00+09:00',
        'icon': '🚕',
        'address': '봉천동 → 역삼동',
    },
    {
        'id': 't5',
        'cardId': '10612',
        'merchantName': '올리브영 강남타운점',
        'category': '뷰티',
        'amount': -38500,
        'approvedAt': '2026-06-21T18:34:00+09:00',
        'icon': '💄',
        'address': '서울 강남구 강남대로 408',
    },
    {
        'id': 't6',
        'cardId': '10609',
        'merchantName': 'CGV 용산아이파크몰',
        'category': '문화',
        'amount': -32000,
        'approvedAt': '2026-06-21T20:10:00+09:00',
        'icon': '🎬',
        'address': '서울 용산구 한강대로23길 55',
    },
    {
        'id': 't7',
        'cardId': '10612',
        'merchantName': '무신사 스토어',
        'category': '쇼핑',
        'amount': -86400,
        'approvedAt': '2026-06-20T23:41:00+09:00',
        'icon': '🛍️',
        'address': '온라인 결제',
    },
    {
        'id': 't8',
        'cardId': '10612',
        'merchantName': '쿠팡 로켓배송',
        'category': '쇼핑',
        'amount': -74200,
        'approvedAt': '2026-06-20T00:27:00+09:00',
        'icon': '📦',
        'address': '온라인 결제',
    },
    {
        'id': 't9',
        'cardId': '10029',
        'merchantName': '인하대학교 생활협동조합',
        'category': '식비',
        'amount': -7800,
        'approvedAt': '2026-06-19T13:05:00+09:00',
        'icon': '🍱',
        'address': '인천 미추홀구 인하로 100',
    },
    {
        'id': 't10',
        'cardId': '10029',
        'merchantName': '공항철도·수도권전철',
        'category': '교통',
        'amount': -6250,
        'approvedAt': '2026-06-19T09:12:00+09:00',
        'icon': '🚇',
        'address': '봉천역 ↔ 인하대역',
    },
    {
        'id': 't11',
        'cardId': '10029',
        'merchantName': '스타벅스 인하대점',
        'category': '카페',
        'amount': -5900,
        'approvedAt': '2026-06-19T15:36:00+09:00',
        'icon': '☕',
        'address': '인천 미추홀구 인하로 67',
    },
    {
        'id': 't12',
        'cardId': '10612',
        'merchantName': 'GS25 봉천역점',
        'category': '편의점',
        'amount': -6800,
        'approvedAt': '2026-06-18T23:12:00+09:00',
        'icon': '🏪',
        'address': '서울 관악구 남부순환로 1728',
    },
    {
        'id': 't13',
        'cardId': '10029',
        'merchantName': '배달의민족 봉천동',
        'category': '식비',
        'amount': -24500,
        'approvedAt': '2026-06-18T20:28:00+09:00',
        'icon': '🍕',
        'address': '온라인 결제',
    },
    {
        'id': 't14',
        'cardId': '10612',
        'merchantName': '네이버플러스 멤버십',
        'category': '구독',
        'amount': -4900,
        'approvedAt': '2026-06-18T00:10:00+09:00',
        'icon': '📱',
        'address': '온라인 결제',
    },
    {
        'id': 't15',
        'cardId': '10609',
        'merchantName': '토익스피킹 응시료',
        'category': '교육',
        'amount': -84000,
        'approvedAt': '2026-06-17T16:22:00+09:00',
        'icon': '📚',
        'address': '온라인 결제',
    },
    {
        'id': 't16',
        'cardId': '10609',
        'merchantName': '링글 영어회화',
        'category': '교육',
        'amount': -29000,
        'approvedAt': '2026-06-17T10:15:00+09:00',
        'icon': '🗣️',
        'address': '온라인 결제',
    },
    {
        'id': 't17',
        'cardId': '10609',
        'merchantName': '교보문고 강남점',
        'category': '교육',
        'amount': -18500,
        'approvedAt': '2026-06-16T19:04:00+09:00',
        'icon': '📖',
        'address': '서울 강남구 강남대로 465',
    },
    {
        'id': 't18',
        'cardId': '10029',
        'merchantName': '단기 알바비 입금',
        'category': '수입',
        'amount': 860000,
        'approvedAt': '2026-06-16T09:00:00+09:00',
        'icon': '💰',
        'address': '-',
    },
]

PURCHASE_PLANS = [
    {
        'title': '취업 준비 지출 계획',
        'type': '취업 준비',
        'expenseMode': 'planned-extra',
        'totalBudget': 800000,
        'startMonth': '2026-07',
        'endMonth': '2026-08',
        'status': '선택 완료',
        'selectedScenarioId': 'sc1',
        'progress': 100,
        'items': [
            {'id': 'i1', 'name': '정장 셔츠·슬랙스', 'category': '쇼핑', 'amount': 210000, 'targetMonth': '2026-07', 'required': True, 'flexible': False},
            {'id': 'i2', 'name': '구두', 'category': '쇼핑', 'amount': 160000, 'targetMonth': '2026-07', 'required': True, 'flexible': True},
            {'id': 'i3', 'name': '증명사진', 'category': '취업', 'amount': 50000, 'targetMonth': '2026-07', 'required': True, 'flexible': False},
            {'id': 'i4', 'name': '어학 응시료', 'category': '교육', 'amount': 84000, 'targetMonth': '2026-08', 'required': True, 'flexible': False},
            {'id': 'i5', 'name': '면접 교통비', 'category': '교통', 'amount': 90000, 'targetMonth': '2026-08', 'required': False, 'flexible': True},
        ],
        'scenarios': [
            {
                'id': 'sc1',
                'type': '혜택 최대화',
                'recommended': True,
                'totalAmount': 594000,
                'totalBenefit': 39520,
                'budgetDiff': 206000,
                'maxMonthlySpend': 420000,
                'achievedCards': 2,
                'reasons': ['쇼핑 결제는 카드의정석2 SHOPPER로 집중', '교통과 카페는 LOCA 100으로 일상 할인 유지'],
                'warning': None,
                'monthlyPlan': [
                    {
                        'month': '2026-07',
                        'items': [
                            {'name': '정장 셔츠·슬랙스', 'amount': 210000, 'card': '카드의정석2 SHOPPER', 'benefit': 21000, 'note': '온라인 쇼핑 혜택과 실적을 함께 반영합니다.', 'status': '구매 예정'},
                            {'name': '구두', 'amount': 160000, 'card': '카드의정석2 SHOPPER', 'benefit': 16000, 'note': '쇼핑 지출을 한 카드에 모아 혜택 누락을 줄입니다.', 'status': '구매 예정'},
                            {'name': '증명사진', 'amount': 50000, 'card': 'LOCA 100', 'benefit': 750, 'note': '소액 오프라인 결제는 기본 할인 카드로 처리합니다.', 'status': '예약 예정'},
                        ],
                    },
                    {
                        'month': '2026-08',
                        'items': [
                            {'name': '어학 응시료', 'amount': 84000, 'card': '이마트 신한카드', 'benefit': 420, 'note': '교육비는 혜택보다 지출 기록의 분류 정확도를 우선합니다.', 'status': '결제 예정'},
                            {'name': '면접 교통비', 'amount': 90000, 'card': 'LOCA 100', 'benefit': 900, 'note': '면접 동선이 늘어나는 달에는 교통비를 따로 추적합니다.', 'status': '사용 예정'},
                        ],
                    },
                ],
                'cardSummary': [
                    {'cardName': 'LOCA 100', 'totalAmount': 140000, 'benefit': 1650, 'achieved': False, 'remainingLimit': 608350, 'itemCount': 2},
                    {'cardName': '카드의정석2 SHOPPER', 'totalAmount': 370000, 'benefit': 37000, 'achieved': True, 'remainingLimit': 0, 'itemCount': 2},
                    {'cardName': '이마트 신한카드', 'totalAmount': 84000, 'benefit': 420, 'achieved': False, 'remainingLimit': 315580, 'itemCount': 1},
                ],
                'aiExplanation': '취업 준비 지출은 쇼핑과 교육으로 나뉩니다. 쇼핑 결제는 SHOPPER에 모아 혜택을 선명하게 만들고, 교통·소액 결제는 LOCA 100으로 정리하는 구성이 적합합니다.',
            }
        ],
    }
]


def serialize_transaction(transaction):
    approved_at = transaction['approvedAt']
    date, time = approved_at[0:10], approved_at[11:16]
    amount = transaction['amount']
    return {
        **transaction,
        'card_id': transaction['cardId'],
        'merchant_name': transaction['merchantName'],
        'cat': transaction['category'],
        'amt': amount,
        'approved_at': approved_at,
        'date': date,
        'time': time,
        'addr': transaction['address'],
        'isCancelled': False,
        'is_cancelled': False,
    }
