"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip().lstrip('\ufeff')
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


load_env_file(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-d#m4ume0fm!(b9)j518qm_zi-fqhjfso7w91&@rw=xlvq0np5_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,testserver')


# Application definition

INSTALLED_APPS = [
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'api.middleware.SimpleCorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

PROJECT_ROOT = BASE_DIR.parent
raw_data_bundle_dir = os.environ.get('CARD_DATA_BUNDLE_DIR')
DATA_BUNDLE_DIR = Path(raw_data_bundle_dir) if raw_data_bundle_dir else None
if DATA_BUNDLE_DIR is None:
    repo_bundle = PROJECT_ROOT / 'pjt-08-db-bundle-20260529'
    local_bundle = PROJECT_ROOT.parent / 'pjt-08-db-bundle-20260529'
    DATA_BUNDLE_DIR = repo_bundle if repo_bundle.exists() else local_bundle

CARD_MASTER_DB = Path(os.environ.get('CARD_MASTER_DB') or (DATA_BUNDLE_DIR / 'card_master_api.sqlite'))
CARD_IMAGE_DIR = Path(os.environ.get('CARD_IMAGE_DIR') or (DATA_BUNDLE_DIR / 'card_images'))

AI_MODE = os.environ.get('AI_MODE', 'mock').lower()
GMS_API_KEY = os.environ.get('GMS_API_KEY') or os.environ.get('OPENAI_API_KEY') or ''
GMS_BASE_URL = os.environ.get(
    'GMS_BASE_URL',
    'https://gms.ssafy.io/gmsapi/api.openai.com/v1',
).rstrip('/')
GMS_MODEL = os.environ.get('GMS_MODEL') or os.environ.get('OPENAI_MODEL') or 'gpt-5-mini'
GMS_FALLBACK_MODEL = os.environ.get('GMS_FALLBACK_MODEL', 'gpt-5.4-mini')
GMS_TIMEOUT_SECONDS = int(os.environ.get('GMS_TIMEOUT_SECONDS', '45'))
GMS_MAX_OUTPUT_TOKENS = int(os.environ.get('GMS_MAX_OUTPUT_TOKENS', '3000'))

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://127.0.0.1:5175').rstrip('/')
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    ','.join([
        FRONTEND_URL,
        'http://127.0.0.1:5173',
        'http://127.0.0.1:5175',
        'http://localhost:5173',
        'http://localhost:5175',
    ]),
)
AUTH_SESSION_DAYS = int(os.environ.get('AUTH_SESSION_DAYS', '14'))
EMAIL_AUTH_ENABLED = os.environ.get('EMAIL_AUTH_ENABLED', 'true').lower() in {'1', 'true', 'yes'}
DEV_AUTO_LOGIN_ENABLED = env_bool('DEV_AUTO_LOGIN_ENABLED', DEBUG)
DEV_ADMIN_EMAIL = os.environ.get('DEV_ADMIN_EMAIL', 'admin@carch.local').strip().lower()
DEV_ADMIN_PASSWORD = os.environ.get('DEV_ADMIN_PASSWORD', 'Carchadmin123!')
DEV_ADMIN_NAME = os.environ.get('DEV_ADMIN_NAME', 'CARCH 관리자')
KAKAO_CLIENT_ID = os.environ.get('KAKAO_REST_API_KEY') or os.environ.get('KAKAO_CLIENT_ID') or ''
KAKAO_CLIENT_SECRET = os.environ.get('KAKAO_CLIENT_SECRET', '')
NAVER_CLIENT_ID = os.environ.get('NAVER_CLIENT_ID', '')
NAVER_CLIENT_SECRET = os.environ.get('NAVER_CLIENT_SECRET', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
